import {Colors, hp, wp} from './colors';

export const STYLES = {
  textHeader: {
    fontSize: wp(3.5),
    color: Colors.inputTextColor,
    textAlign: 'center',
    textTransform: 'uppercase',
    fontFamily: 'Gilroy-Bold',
  },
  common: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperStyle: {
    stepIndicatorSize: hp(6),
    currentStepIndicatorSize: hp(6),
    separatorStrokeWidth: hp(0.1),
    currentStepStrokeWidth: hp(0.1),
    stepStrokeCurrentColor: Colors.darkBlue,
    stepStrokeWidth: hp(0.1),
    stepStrokeFinishedColor: Colors.darkBlue,
    stepStrokeUnFinishedColor: '#DEDEDE',
    separatorFinishedColor: Colors.darkBlue,
    separatorUnFinishedColor: '#aaaaaa',
    stepIndicatorFinishedColor: Colors.white,
    stepIndicatorUnFinishedColor: '#DEDEDE',
    stepIndicatorCurrentColor: Colors.darkBlue,
  },
  modalHeader: {
    fontFamily: 'Gilroy-Bold',
    color: Colors.inputTextColor,
    fontSize: wp(4),
    marginTop: 25,
    marginBottom: 10,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  simpleText: {
    color: Colors.inputTextColor,
    fontSize: wp(3.8),
    marginTop: hp(3),
    marginBottom: hp(2),
    marginHorizontal: wp(10),
    textAlign: 'center',
  },
  tabView: {
    height: hp(7),
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    borderBottomWidth: 0.8,
    borderTopWidth: 0.8,
    borderColor: '#ACABCD',
  },
  staticLabel: {
    fontFamily: 'Gilroy-Bold',
    fontSize: wp(4),
    color: Colors.inputTextColor,
  },
  mapPinCircle: {
    height: wp(12),
    width: wp(12),
    borderRadius: wp(6),
    backgroundColor: Colors.pageBG,
    alignItems: 'center',
    justifyContent: 'center',
  },
  separatorView: {
    borderWidth: 0.8,
    borderColor: Colors.silver,
    width: '100%',
    marginTop: hp(2),
  },
  flexBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(2),
  },
  leftText: {
    fontFamily: 'Gilroy-SemiBold',
    fontSize: wp(4.3),
    color: Colors.inputTextColor,
    textTransform: 'uppercase',
  },
  rightText: {
    fontFamily: 'Roboto-Bold',
    fontSize: wp(4.5),
    color: Colors.inputTextColor,
    width: '50%',
    textAlign: 'right',
  },
  inputForm: {
    marginHorizontal: wp(5),
    paddingVertical: wp(5),
    paddingHorizontal: wp(5),
    borderWidth: 1,
    borderRadius: 15,
    backgroundColor: Colors.white,
    borderColor: '#DEE6ED',
    marginTop: hp(2),
  },
  tabText: {
    fontSize: wp(4),
    fontFamily: 'Gilroy-Bold',
  },
  selectionView: {
    height: hp(12),
    width: hp(12),
    borderRadius: hp(6),
    backgroundColor: '#F2E6FF',
    borderColor: Colors.darkBlue,
  },
  selectionText: {
    fontFamily: 'Gilroy-SemiBold',
    fontSize: wp(4),
    color: '#3B4B58',
    marginTop: hp(1),
  },
  participatedText: {
    color: Colors.darkBlue,
    fontSize: hp(2.8),
    fontFamily: 'Gilroy-SemiBold',
  },
  priceView: {
    backgroundColor: Colors.pageBG,
    width: '45%',
    height: hp(5),
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
};
